### ISSUE TITLE
ExerciseStatus cache triggers duplicate key errors

### ISSUE THREAD

**Issue by thepieterdc** [dodona-edu/dodona#1877]
**Request:**
`GET /nl/series/2281/exercises.json`

**Exception:**
`Mysql2::Error: Duplicate entry for key `index_exercise_statuses_on_exercise_id_and_series_id_and_user_id'`

**Trace**
app/models/exercise.rb:423:in `exercise_status_for'
app/models/exercise.rb:338:in `best_is_last_submission?'
app/views/exercises/_exercise.json.jbuilder:8
app/views/exercises/index.json.jbuilder:1
app/controllers/application_controller.rb:165:in `user_time_zone'

**Comment by thepieterdc** [comment]
This issue has been identified as a race condition and was fixed by retrying the `find` operation once.
