### ISSUE TITLE
Invalid dirconfigs cause reprocessing to crash

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#2259]
Invalid dirconfigs cause reprocessing (and probably everything that reads the config) to crash

**Comment by chvp** [comment]
Relevant backtrace:
```
  app/models/repository.rb:238:in `rescue in read_config_file'
  app/models/repository.rb:233:in `read_config_file'
  app/models/activity.rb:401:in `read_dirconfig'
  app/models/activity.rb:182:in `block in merged_dirconfig'
  app/models/activity.rb:182:in `each'
  app/models/activity.rb:182:in `map'
  app/models/activity.rb:182:in `merged_dirconfig'
  app/models/activity.rb:197:in `merged_config'
  app/models/repository.rb:180:in `update_activity'
  app/models/repository.rb:129:in `block in process_activities'
  app/models/repository.rb:126:in `each'
  app/models/repository.rb:126:in `process_activities'
  app/models/repository.rb:96:in `process_activities_email_errors'
  app/controllers/repositories_controller.rb:175:in `reprocess'
  app/controllers/application_controller.rb:176:in `user_time_zone'
```

**Comment by chvp** [comment]
This is a race condition that can only be triggered when a repository is pushed to in rapid succession and the second push contains an invalid dirconfig file. Users are still notified about this invalid file by the processing of the second push, and this happens quite rarely. After internal discussion we decided that fixing this isn't worth the added complexity.
