### ISSUE TITLE
CSP error on exercise pages

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#2642]
Exercise pages throw a CSP error in google chrome.

```
application-a34a604ee16d11783ea4f72da5b7a3438961e72f0d6c581c4c67cbe1aec34eae.js:52 Refused to create a worker from 'blob:https://dodona.ugent.be/fc102418-58dc-4439-b6a1-38d08d74055b' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com https://cdn.jsdelivr.net/npm/mathjax@3/". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.
```
and
```
Could not load worker DOMException: Failed to construct 'Worker': Access to the script at 'blob:https://dodona.ugent.be/fc102418-58dc-4439-b6a1-38d08d74055b' is denied by the document's Content Security Policy.
    at n (https://dodona.ugent.be/assets/application-a34a604ee16d11783ea4f72da5b7a3438961e72f0d6c581c4c67cbe1aec34eae.js:52:28568)
    at l.$createWorkerFromOldConfig (https://dodona.ugent.be/assets/application-a34a604ee16d11783ea4f72da5b7a3438961e72f0d6c581c4c67cbe1aec34eae.js:52:29403)
    at new l (https://dodona.ugent.be/assets/application-a34a604ee16d11783ea4f72da5b7a3438961e72f0d6c581c4c67cbe1aec34eae.js:52:28765)
    at l.createWorker (https://dodona.ugent.be/assets/ace/mode-javascript-42fbcc249cd6a7090266f701e8b7adca401f91835d6f978c76a97f81b2c85888.js:1:17830)
    at f.$startWorker (https://dodona.ugent.be/assets/application-a34a604ee16d11783ea4f72da5b7a3438961e72f0d6c581c4c67cbe1aec34eae.js:47:19561)
    at f.$onChangeMode (https://dodona.ugent.be/assets/application-a34a604ee16d11783ea4f72da5b7a3438961e72f0d6c581c4c67cbe1aec34eae.js:47:18820)
    at f.<anonymous> (https://dodona.ugent.be/assets/application-a34a604ee16d11783ea4f72da5b7a3438961e72f0d6c581c4c67cbe1aec34eae.js:47:18570)
    at https://dodona.ugent.be/assets/application-a34a604ee16d11783ea4f72da5b7a3438961e72f0d6c581c4c67cbe1aec34eae.js:44:22407
    at Array.forEach (<anonymous>)
    at https://dodona.ugent.be/assets/application-a34a604ee16d11783ea4f72da5b7a3438961e72f0d6c581c4c67cbe1aec34eae.js:44:22384
```

I think the ACE editor is trying to use a worker.

**Comment by bmesuere** [comment]
This is only the case for javascript exercises.
