### ISSUE TITLE
Avoid duplicate key error for activity statuses

### ISSUE THREAD

**Issue by jorg-vr** [dodona-edu/dodona#4479]
Activity status sometimes get created in a delayed job. Depending on the user activity, it could happen that the activity status is already created in the meantime.

It also tends to happen on `submission#create`, possibly by two new submission happening close to each other 
```
app/models/activity.rb:451:in `activity_status_for!'
app/models/activity.rb:445:in `activity_status_for'
app/models/activity.rb:344:in `activity_statuses_for'
app/models/submission.rb:295:in `update_exercise_status'
app/models/submission.rb:222:in `evaluate_delayed'
app/controllers/submissions_controller.rb:124:in `create'
app/controllers/application_controller.rb:190:in `user_time_zone'
```

We should replace this by a `find_or_create` to avoid the error

**Comment by jorg-vr** [comment]
The related pr has been reverted because of other issues
